pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/PedroCosta083/php_jenkins_docker_integration.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                bat 'C:\\composer\\composer install'  // Usando o caminho do Composer corretamente
            }
        }
        stage('Run Tests') {
            steps {
                bat 'C:\\wamp64\\bin\\php\\php8.3.6\\phpunit --configuration phpunit.xml'
            }
        }
    }
    post {
        always {
            echo 'Cleaning up...'
        }
    }
}
